### ISSUE TITLE
Alert dont work

### ISSUE THREAD

**Issue by Zael98** [qbcore-framework/qb-jewelery#16]
When i steal the jwelery the police dont recibe any alert. I see the server and clients error and i dont have any error. anyone can tell me why?

**Comment by GeekHamza1** [comment]
SAME Issue here
the script is configured for  linden_outlawalerts   not qb-policealerts

**Comment by Zael98** [comment]
Update to the last qb-jewelery and the last qb-phone and is fixed. The lasts updates works for me

**Comment by GeekHamza1** [comment]
i updated qb-police and qb-jewelery as you said 
and still not receiving alerts

**Comment by Zael98** [comment]
nooo, u need update qb-jewelery and qb-phone, not police.  I did it and for me work

**Comment by GeekHamza1** [comment]
i updated it also\

what alerts you using ?

**Comment by Zael98** [comment]
the defaults of the qb-core. police:client:addalert. work in qbcore server. Look in qbcore server where is the police addalert function probably something is bad there.
